### PR TITLE
Completed your project

### PR DESCRIPTION
**Pull request by ghost**
*Merged the changes Gyan made....But couldn't get the font alright

### CODE REVIEW

**Comment by manu-chroma** [comment]
@harshitbudhraja Thanks for "completing our project". 

@gyanl Checkout https://harshitbudhraja.github.io/onlineClock/
I don't think you wanted the alarm the way he has implemented. Suggest the relevant edits you want.

**Comment by ghost** [comment]
@gyanl I should just make a guess that you wanted the whole background colour or something to be changed/highlighted when the alarm sounds ? :sweat_smile:

**Comment by gyanl** [comment]
Hey @harshitbudhraja - thanks for helping out!

The code you wrote doesn't seem to be working. Can you confirm that it works, and make alarm.mp3 ring when the alarm time is reached? Use the latest gh-pages branch on my profile if you can, I have made a lot of changes to the html/css so if you use your branch it'll be difficult to resolve the conflicts.

**Comment by ghost** [comment]
@gyanl I would look into that. It seemed to work perfectly when I committed the changes. I'm afraid the indentation change might have caused that problem !

**Comment by gyanl** [comment]
Fixed the conflicts and merged. Thanks!

**Pull request closed without merging**
